namespace TransportApi.Common;

public static class Constants
{
    public static readonly HashSet<string> MetropolitanStations = [
        "Allawah",
        "Arncliffe",
        "Artarmon",
        "Asquith",
        "Banksia",
        "Bankstown",
        "Bardwell Park",
        "Beecroft",
        "Berala",
        "Berowra",
        "Beverly Hills",
        "Bexley North",
        "Birrong",
        "Blacktown",
        "Bondi Junction",
        "Cabramatta",
        "Carlton",
        "Campbelltown",
        "Canley Vale",
        "Caringbah",
        "Carramar",
        "Casula",
        "Central",
        "Chatswood",
        "Chester Hill",
        "Circular Quay",
        "Clarendon",
        "Concord West",
        "Cronulla",
        "Denistone",
        "Doonside",
        "East Richmond",
        "East Hills",
        "Eastwood",
        "Edgecliff",
        "Edmondson Park",
        "Emu Plains",
        "Engadine",
        "Erskineville",
        "Flemington",
        "Granville",
        "Green Square",
        "Gymea",
        "Harris Park",
        "Heathcote",
        "Homebush",
        "Hornsby",
        "Hurstville",
        "Ingleburn",
        "Jannali",
        "Killara",
        "Kings Cross",
        "Kingsgrove",
        "Kirrawee",
        "Kogarah",
        "Leightonfield",
        "Leppington",
        "Leumeah",
        "Lidcombe",
        "Lindfield",
        "Macarthur",
        "Macdonaldtown",
        "Macquarie Fields",
        "Marayong",
        "Martin Place",
        "Mascot",
        "Merrylands",
        "Milsons Point",
        "Minto",
        "Miranda",
        "Mortdale",
        "Mount Colah",
        "Mount Druitt",
        "Mount Kuring-gai",
        "Mulgrave",
        "Museum",
        "Narwee",
        "Newtown",
        "Normanhurst",
        "North Strathfield",
        "North Sydney",
        "Oatley",
        "Panania",
        "Parramatta",
        "Pendle Hill",
        "Pennant Hills",
        "Penshurst",
        "Petersham",
        "Pymble",
        "Quakers Hill",
        "Redfern",
        "Regents Park",
        "Revesby",
        "Rhodes",
        "Richmond",
        "Riverstone",
        "Riverwood",
        "Rockdale",
        "Rooty Hill",
        "Schofields",
        "Sefton",
        "Seven Hills",
        "St James",
        "St Leonards",
        "St Peters",
        "Strathfield",
        "Summer Hill",
        "Sutherland",
        "Sydenham",
        "Tempe",
        "Thornleigh",
        "Toongabbie",
        "Town Hall",
        "Turramurra",
        "Turrella",
        "Villawood",
        "Vineyard",
        "Wahroonga",
        "Waitara",
        "Warrawee",
        "Warwick Farm",
        "Waverton",
        "Wentworthville",
        "Werrington",
        "West Ryde",
        "Westmead",
        "Wolli Creek",
        "Wollstonecraft",
        "Woolooware",
        "Wynyard",
        "Yagoona",
        "Yennora",
    ];
}

public static class Mappings
{
    public static readonly Dictionary<string, string> UrlMappings = new()
    {
        { "Metro", "metro" },
        { "Rail", "sydneytrains" },
    };
}