public static class Constants
{
    public static HashSet<string> MetropolitanStations = [
        "Allawah",
        "Arncliffe",
        "Artarmon",
        "Asquith",
        "Banksia",
        "Bankstown",
        "Bardwell Park",
        "Beecroft",
        "Berala",
        "Berowra",
        "Beverly Hills",
        "Bexley North",
        "Birrong",
        "Blacktown",
        "Bondi Junction",
        "Cabramatta",
        "Campbelltown",
        "Canley Vale",
        "Caringbah",
        "Carramar",
        "Casula",
        "Chatswood",
        "Chester Hill",
        "Circular Quay",
        "Clarendon",
        "Concord West",
        "Cronulla",
        "Denistone",
        "Doonside",
        "East Hills",
        "Eastwood",
        "Edgecliff",
        "Edmondson Park",
        "Emu Plains",
        "Engadine",
        "Erskineville",
        "Flemington",
        "Granville",
        "Green Square",
        "Gymea",
        "Harris Park",
        "Heathcote",
        "Helensburgh",
        "Homebush",
        "Hornsby",
        "Hurstville",
        "Ingleburn",
        "Jannali",
        "Killara",
        "Kingsgrove",
        "Kirrawee",
        "Kogarah",
        "Leightonfield",
        "Leppington",
        "Leumeah",
        "Lidcombe",
        "Lindfield",
        "Macarthur",
        "Macdonaldtown",
        "Macquarie Fields",
        "Marayong",
        "Martin Place",
        "Mascot",
        "Merrylands",
        "Milsons Point",
        "Minto",
        "Miranda",
        "Mortdale",
        "Mount Colah",
        "Mount Druitt",
        "Mount Kuring-gai",
        "Mulgrave",
        "Museum",
        "Narwee",
        "Normanhurst",
        "North Strathfield",
        "North Sydney",
        "Oatley",
        "Panania",
        "Parramatta",
        "Pendle Hill",
        "Pennant Hills",
        "Petersham",
        "Pymble",
        "Quakers Hill",
        "Redfern",
        "Regents Park",
        "Revesby",
        "Rhodes",
        "Riverstone",
        "Riverwood",
        "Rockdale",
        "Rooty Hill",
        "Schofields",
        "Sefton",
        "Seven Hills",
        "St Leonards",
        "St Peters",
        "Strathfield",
        "Summer Hill",
        "Sutherland",
        "Tempe",
        "Thornleigh",
        "Toongabbie",
        "Turramurra",
        "Turrella",
        "Villawood",
        "Vineyard",
        "Wahroonga",
        "Waitara",
        "Warrawee",
        "Warwick Farm",
        "Wentworthville",
        "Werrington",
        "West Ryde",
        "Westmead",
        "Wolli Creek",
        "Wollstonecraft",
        "Woolooware",
        "Yagoona",
        "Yennora",
    ];
}